### ISSUE TITLE
cloning issue

### ISSUE THREAD

**Issue by saeedmozafari** [ForzaETH/race_stack#18]
Hi
Some of sub modules like ccma and f110-simulator can not be cloned with the following command:

git clone --recurse-submodules  https://github.com/ForzaETH/race_stack.git

for example the folder of ccma is empty after cloning to the race stack. Whats the problem? should I download it separately?

**Comment by niciBume** [comment]
That should actually work this way. In case you had the repo installed before we added predictive spliner etc. you would probably have to reinitialize:

`git submodule init`
`git submodule update`

We also just changed the ontrack sysID submodule to use https clone instead of ssh which could have also been a source of error. Could you try cloning again in a new folder space?
