### ISSUE TITLE
map editor

### ISSUE THREAD

**Issue by DDKAPQ** [ForzaETH/race_stack#19]
Hi
when I do SLAM with mapping.launch and rviz looks pretty well so
In the next window that pops up after pressing y, the inverted screen for the center line was not created properly, so I thought the border of the map was not clear, so I tried to work with png directly through the map editor, However, the appearance of the saved png file was also saved as an inverted map, different from the appearance of the map in rviz. It looks like GIMP work will be difficult with this file. Is the result correct?

**Comment by niciBume** [comment]
Hi, can you show the map image?

**Comment by DDKAPQ** [comment]
This is what the png file looks like when saving the map using 
roslaunch stack_master mapping.launch map_name:=<map name of choice> racecar_version:=<NUCX>
after the actual track and slam.

and also when I doing 
roslaunch map_editor map_editor.launch map_name:=PLACE_DATE_VN map_editor_mapping:=True
This is not saved as a pgm file for direct map editing, but as a png file.

![IMG_9678](https://github.com/user-attachments/assets/1f0e57b8-932d-404c-bed0-5fd8bd5fc03f)

![b1](https://github.com/user-attachments/assets/60d92a1e-91c2-48cf-996d-2e16b2db8c28)

**Comment by niciBume** [comment]
I see. Using black tubes is difficult for the LiDAR as it does not reflect as much (see: https://arxiv.org/pdf/2309.10504). 

Hence when mapping you need to drive multiple times to get a good map. Probably the SLAM did not get a nice occupancy grid, that's why the part with the white wall is visible in the png but it has problems with the black only sections.

Different things you can do:

- Adapt the SLAM config [here](https://github.com/ForzaETH/race_stack/blob/main/stack_master/config/NUC2/slam/f110_2d_loc.lua) for bad reflectivity based on the [docs](https://google-cartographer-ros.readthedocs.io/en/latest/tuning.html) and redo the mapping
- Redo the mapping and drive slowly and multiple times
- You don't need tubes, you can draw an arbitrary map in GIMP. I.e. you could just "finish" the current png. This will not represent the tubes accurately, but then again, technically you don't need them, as localisation is performed with the .pbstream and the track is only needed to compute the racing line

**Comment by niciBume** [comment]
Should all be saved as png. Check out some additional info in the readme: https://github.com/ForzaETH/race_stack/tree/main/f110_utils/nodes/map_editor
